version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - zilliqa{{ checksum "Gemfile.lock" }}
            - zilliqa

      - run:
          name: Install libsecp256k1-dev dependency
          command: sudo apt-get update -y && sudo apt-get install -y libsecp256k1-dev

      - run:
          name: Bundle Install
          command: bundle install
      - save_cache:
          key: zilliqa{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake test
