name: CI

on:
  pull_request:
    types: [opened, labeled, reopened, synchronize]
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          rubygems: latest
          bundler-cache: true
      - uses: actions/checkout@v3
      - run: sudo apt-get update -y && sudo apt-get install -y libsecp256k1-dev
      - run: bundle install
      - run: bundle exec rake test
